input_folder: assemblies_sample
output_folder: assemblies_sample_out
probe_length: 21
proportion_of_match_in_probes_to_say_SNPs_are_the_same: 0.95
mem_mb:
  - 1000
  - 5000
  - 10000
mem_mb_heavy_jobs:
  - 25000
  - 50000
  - 75000
